# Generated by Django 4.2.16 on 2024-10-09 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='id_pago',
        ),
    ]
